### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by FeryET** [MLProductionHub/education-hub#1]
Please ping me in this issue thread and I will add you to the team.

**Comment by aminjamshidi** [comment]
I am amin jamshidi (Intern of Aimedic  from Project stopped(breast cancer)
I want to join this team

**Comment by yashar7799** [comment]
@FeryET

**Comment by aminjamshidi** [comment]
@FeryET

**Comment by mhkoosheshi** [comment]
@FeryET

**Comment by yashar7799** [comment]
> Please ping me in this issue thread and I will add you to the team.

@FeryET

**Comment by alish1377** [comment]
@FeryET 

>

**Comment by mhosseinkarimi** [comment]
@FeryET

**Comment by alihg96** [comment]
@FeryET

**Comment by arghavansouki** [comment]
@FeryET

**Comment by Mohammadhesaam** [comment]
@FeryET

**Comment by Sarmeili** [comment]
@FeryET

**Comment by arashHarirpoosh** [comment]
@FeryET

**Comment by kimiaghodoosi** [comment]
@FeryET

**Comment by hmd78** [comment]
@FeryET
